
//*** Do not edit ****
//*** Automatically generated by make_version ***

char *vstr = "ibp_server(no FIFO): v1.0.1p1\n"
             "Date: Thu Mar 20 15:39:50 CDT 2008\n"
             "gcc (GCC) 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)\n"
             "Host: alandepot1.reddnet.org\n"
             "OS: 2.6.22-14-server #1 SMP Tue Feb 12 03:10:53 UTC 2008 x86_64\n";

char *ibp_version() {
    return(vstr);
}

