//*** Do not edit ****
//*** Automatically generated by cmake ***
 
const char *vstr = "ibp_server(no FIFO): v1.5.3\n"
             "CMake Build Date: Mon Aug 12 13:18:27 EDT 2013\n"
             "Compiler: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)\n"
             "Compile Flags(Debug):   -O2 -Wall -g -D_ENABLE_DEBUG -DHAVE_CONFIG_H -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_ENABLE_PHOEBUS\n"
             "Build Host: localhost.localdomain\n"
             "Build OS: Linux-2.6.32-358.14.1.el6.x86_64-x86_64\n";        

const char *server_version() {
    return(vstr);
}

   

